# name: React Runtime Tests

# on:
#   push:
#     branches:
#       - develop
#       - main
#   pull_request:
#     branches:
#       - develop
#       - main

# jobs:
#   install_dependencies:
#     name: Install Dependencies
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout Repository
#         uses: actions/checkout@v4

#       - name: Setup Node.js
#         uses: actions/setup-node@v4
#         with:
#           node-version: 20
#           cache: 'npm'
#           cache-dependency-path: uor-mts-frontend/package-lock.json

#       - name: Install Dependencies
#         run: npm ci
#         working-directory: uor-mts-frontend  # ✅ Now installs dependencies inside the correct folder

#   type_check:
#     name: Type Checking
#     runs-on: ubuntu-latest
#     needs: install_dependencies
#     steps:
#       - name: Checkout Repository
#         uses: actions/checkout@v4

#       - name: Setup Node.js
#         uses: actions/setup-node@v4
#         with:
#           node-version: 20

#       - name: Install Dependencies
#         run: npm ci
#         working-directory: uor-mts-frontend

#       - name: Run TypeScript Type Check
#         run: npm run type-check
#         working-directory: uor-mts-frontend  # ✅ Ensures it runs inside the correct project folder

#   test:
#     name: Run Jest Tests
#     runs-on: ubuntu-latest
#     needs: type_check  # ✅ Ensures type check passes before running tests
#     steps:
#       - name: Checkout Repository
#         uses: actions/checkout@v4

#       - name: Setup Node.js
#         uses: actions/setup-node@v4
#         with:
#           node-version: 20

#       - name: Install Dependencies
#         run: npm ci
#         working-directory: uor-mts-frontend

#       - name: Run Tests
#         run: npm test -- --coverage
#         working-directory: uor-mts-frontend  # ✅ Runs Jest tests inside the correct folder